services:
  - type: web
    name: my-fastapi-app
    env: python
    runtime: python-3.12.6
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.app:app --host 0.0.0.0 --port $PORT
